spring:
  application:
    name: backend
  mvc:
    apiversion:
      use:
        header: Api-Version
      default: 1.0
server:
  port: 8088

mana-neutron:
  mode: dev #dev, prod
  config:
    setting-path: "./config/setting.json"
    prompt-template-config-path: "./config/prompt-template-config.json"
    default-prompt-path: "./prompt_template/init.txt"
    token-config-path: "./config/token.txt"
    session-path: "./session"
    session-cache-path: "./session/session.json"
